apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-1avw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ivkl-tenant/rhtap-demo-app/hacbs-test-project-1avw@sha256:ae75d45c7936b547bba164049aa8cd191b8981046006a18bfdfc2f2f97cc6d37
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
