apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1avw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1avw
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1avw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1avw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1avw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ivkl-tenant/rhtap-demo-app/hacbs-test-project-1avw@sha256:295717cd98b4e7b64ee8d930183eff521930ba234c2f7dbf591b43fc0949eb00
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
